# -*- coding: utf-8 -*-
"""E-procurement Government of India.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sJLpRuGBJ8ro6ecWmrfbyb6Cx1w7ZQyD
"""

import requests
from bs4 import BeautifulSoup
import csv

# Send a GET request to the website
response = requests.get("https://etenders.gov.in/eprocure/app")


# Check if the request was successful
if response.status_code == 200:
    # Use BeautifulSoup to parse the HTML content
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the table containing the data you want to scrape
    table = soup.find('table')

    # Check if the table was found
    if table:
        # Write the table data to a csv file
        with open('etenders_data.csv', 'w', newline='') as f:
            writer = csv.writer(f)

            # Write the header row
            writer.writerow(['Header 1', 'Header 2', 'Header 3', ...])

            # Write the data rows
            for row in table.find_all('tr'):
                data = [cell.text for cell in row.find_all('td')]
                writer.writerow(data)

# If the request was unsuccessful, print an error message
else:
    print("Error: Could not retrieve data from the website")

